context("Testing shipname normalizing")
library(startR)

test_that("normalize_shipname works properly", {
  expect_true(is.na(normalize_shipname(NA)))
  expect_true(is.na(normalize_shipname("")))
  expect_equal(normalize_shipname("MixEd"), "MIXED")
  expect_equal(normalize_shipname("weird -+%()<>$;!&'`\\.#/"), "WEIRD")
  expect_equal(normalize_shipname("  \tspaced  \nname      "), "SPACEDNAME")
  expect_equal(normalize_shipname("f/b boat f/v othername"), "BOATOTHERNAME")
  expect_equal(normalize_shipname("r/v boat othername"), "BOATOTHERNAME")
  expect_equal(normalize_shipname("no. boat"), "BOAT")
  expect_equal(normalize_shipname("no537 boat"), "BOAT537")
  expect_equal(normalize_shipname("boat IX"), "BOAT9")
  expect_equal(normalize_shipname("a"), "A")
  expect_equal(normalize_shipname("no"), "NO")
})
